version: '''3.9'''
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    networks:
    - testing_net
    volumes:
    - ./server:/config
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=1
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Santiago Lionel
    - APELLIDO=Lorca
    - DOCUMENTO=30904465
    - NACIMIENTO=1999-03-17
    - NUMERO=7574
    networks:
    - testing_net
    depends_on:
    - server
    volumes:
    - ./client:/config
  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=2
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Agustin Emanuel
    - APELLIDO=Zambrano
    - DOCUMENTO=21689196
    - NACIMIENTO=2000-05-10
    - NUMERO=9325
    networks:
    - testing_net
    depends_on:
    - server
    volumes:
    - ./client:/config
  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=3
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Tiago Nicolás
    - APELLIDO=Rivera
    - DOCUMENTO=34407251
    - NACIMIENTO=2001-08-29
    - NUMERO=1033
    networks:
    - testing_net
    depends_on:
    - server
    volumes:
    - ./client:/config
  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=4
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Camila Rocio
    - APELLIDO=Varela
    - DOCUMENTO=37130775
    - NACIMIENTO=1995-05-09
    - NUMERO=4179
    networks:
    - testing_net
    depends_on:
    - server
    volumes:
    - ./client:/config
  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=5
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Diego Agustin
    - APELLIDO=Mamani
    - DOCUMENTO=33259835
    - NACIMIENTO=1991-01-08
    - NUMERO=1931
    networks:
    - testing_net
    depends_on:
    - server
    volumes:
    - ./client:/config
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
